### ISSUE TITLE
Moved

### ISSUE THREAD

**Issue by kj7rrv** [notriddle/botpoison-jerk#1]
Hi, I'm the original developer of BotPoison.
I just wanted to let you know that the URL is now https://scoopgracie.com.
Also, it is a good idea to add a license. Thanks!

**Comment by notriddle** [comment]
Cool! Thanks for the info.

Sorry you lost your old domain.

**Comment by kj7rrv** [comment]
No, I didn't lose it. I wanted this one instead. :)
